[package]
name = "regex-tui"
version = "0.1.0"
authors = ["Jokler <jokler@protonmail.com>"]
edition = "2018"

[dependencies]
crossterm = "0.21.0"
regex = "1.5.4"

[dependencies.tui]
version = "0.16.0"
default-features = false
features = ["crossterm"]
